erDiagram

  PERFIL {
    int prf_id PK
    string prf_nome
    string prf_nivel_acesso
    string prf_descricao
    string prf_status
  }

  USUARIO {
    int usr_id PK
    int prf_id FK
    string usr_nome
    string usr_email
    string usr_login
    string usr_senha_hash
    string usr_status
  }

  ESTACAO_CONTROLE {
    int est_id PK
    string est_nome
    float est_latitude
    float est_longitude
    string est_status
  }

  SATELITE {
    int sat_id PK
    string sat_nome
    string sat_modelo_hardware
    string sat_versao_firmware
    string sat_tipo_orbita
    string sat_status
  }

  CANAL_COMUNICACAO {
    int cnc_id PK
    int est_id FK
    int sat_id FK
    string cnc_nome
    float cnc_frequencia_hz
    string cnc_tipo
    string cnc_protocolo_seguranca
    string cnc_status
  }

  COMANDO {
    int cmd_id PK
    int usr_id FK
    int est_id FK
    int sat_id FK
    string cmd_tipo
    string cmd_descricao
    datetime cmd_data_hora_criacao
    string cmd_status
  }

  COMANDO_PARAMETRO {
    int cmp_id PK
    int cmd_id FK
    string cmp_nome
    string cmp_valor
    string cmp_unidade
    int cmp_ordem
  }

  MENSAGEM {
    int msg_id PK
    int cnc_id FK
    int cmd_id FK
    string msg_tipo
    string msg_prioridade
    string msg_status
    datetime msg_data_hora_geracao
    datetime msg_data_hora_envio
    datetime msg_data_hora_confirmacao
  }

  TELEMETRIA {
    int tlm_id PK
    int sat_id FK
    int msg_id FK
    string tlm_tipo
    string tlm_conteudo
    datetime tlm_data_hora_coleta
    datetime tlm_data_hora_recebimento
    string tlm_status_integridade
  }

  PERFIL           ||--o{ USUARIO           : "classifica"
  USUARIO          ||--o{ COMANDO           : "gera"
  ESTACAO_CONTROLE ||--o{ COMANDO           : "emite"
  SATELITE         ||--o{ COMANDO           : "e destino de"
  COMANDO          ||--o{ COMANDO_PARAMETRO : "possui"
  ESTACAO_CONTROLE ||--o{ CANAL_COMUNICACAO : "opera"
  SATELITE         ||--o{ CANAL_COMUNICACAO : "usa"
  CANAL_COMUNICACAO||--o{ MENSAGEM          : "transmite"
  COMANDO          o|--o{ MENSAGEM          : "gera"
  SATELITE         ||--o{ TELEMETRIA        : "produz"
  MENSAGEM         ||--o{ TELEMETRIA        : "transporta"