"""update_locais_table

Revision ID: 07a40c1d55c2
Revises: ce87f28aaee0
Create Date: 2026-05-26 18:34:14.846854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07a40c1d55c2'
down_revision: Union[str, Sequence[str], None] = 'ce87f28aaee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locais', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('locais', sa.Column('lng', sa.Float(), nullable=False))
    op.add_column('locais', sa.Column('categoria', sa.String(), nullable=False))
    op.add_column('locais', sa.Column('rating', sa.Integer(), nullable=False))
    op.alter_column('locais', 'id_ponto',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('locais', 'tipo',
               existing_type=postgresql.ENUM('RESIDENCIAL', 'COMERCIAL', 'INDUSTRIAL', 'PUBLICO', 'OUTRO', name='tipo_local'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locais', 'tipo',
               existing_type=postgresql.ENUM('RESIDENCIAL', 'COMERCIAL', 'INDUSTRIAL', 'PUBLICO', 'OUTRO', name='tipo_local'),
               nullable=False)
    op.alter_column('locais', 'id_ponto',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('locais', 'rating')
    op.drop_column('locais', 'categoria')
    op.drop_column('locais', 'lng')
    op.drop_column('locais', 'lat')
    # ### end Alembic commands ###
