"""criando_tabela_eventos

Revision ID: 67fbc3d9db91
Revises: 
Create Date: 2026-05-26 21:38:35.060964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67fbc3d9db91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunicacao_eventos',
    sa.Column('evt_id', sa.Integer(), nullable=False),
    sa.Column('evt_data_hora', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evt_tipo', sa.String(), nullable=False),
    sa.Column('evt_satelite_id', sa.String(), nullable=False),
    sa.Column('evt_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evt_status', sa.String(), nullable=False),
    sa.Column('usr_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('evt_id')
    )
    op.create_index(op.f('ix_comunicacao_eventos_evt_id'), 'comunicacao_eventos', ['evt_id'], unique=False)
    op.create_table('perfil',
    sa.Column('prf_id', sa.Integer(), nullable=False),
    sa.Column('prf_nome', sa.String(), nullable=True),
    sa.Column('prf_nivel_acesso', sa.String(), nullable=True),
    sa.Column('prf_descricao', sa.String(), nullable=True),
    sa.Column('prf_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('prf_id')
    )
    op.create_index(op.f('ix_perfil_prf_id'), 'perfil', ['prf_id'], unique=False)
    op.create_table('usuario',
    sa.Column('usr_id', sa.Integer(), nullable=False),
    sa.Column('prf_id', sa.Integer(), nullable=True),
    sa.Column('usr_nome', sa.String(), nullable=True),
    sa.Column('usr_email', sa.String(), nullable=True),
    sa.Column('usr_login', sa.String(), nullable=True),
    sa.Column('usr_senha_hash', sa.String(), nullable=True),
    sa.Column('usr_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('usr_id'),
    sa.UniqueConstraint('usr_email'),
    sa.UniqueConstraint('usr_login')
    )
    op.create_index(op.f('ix_usuario_usr_id'), 'usuario', ['usr_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_usr_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_perfil_prf_id'), table_name='perfil')
    op.drop_table('perfil')
    op.drop_index(op.f('ix_comunicacao_eventos_evt_id'), table_name='comunicacao_eventos')
    op.drop_table('comunicacao_eventos')
    # ### end Alembic commands ###
